require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.6
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/bundle'
    - 'config/*'

Rails:
  Enabled: true

Documentation:
  Enabled: false

# Additional configuration
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
